version: "2"
services:
  web:
    image: 918747151581.dkr.ecr.eu-central-1.amazonaws.com/docker-frontend-backend-db@sha256:6e4716010dabdc869f6f9a64d79db5eb1f696ed45f0b992be01e58878b3e1038
    depends_on:
      - api
    ports:
      - "3000:3000"
  api:
    image: 918747151581.dkr.ecr.eu-central-1.amazonaws.com/docker-frontend-backend-db:latest
    depends_on:
      - mongo
    ports:
      - "3001:3001"
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017

volumes: 
  mongodb_data: